### ISSUE TITLE
Problemi "Crono termostato"

### ISSUE THREAD

**Issue by Paco1960** [morenonew2/HASS_WINET#2]
Ciao Moreno!
Ho acquistato ed installato un modulo WiNET ad una stufa Cola Beauty 13, e funziona, sia in locale (interfaccia web) che via cloud.
Ovviamente ho voluto aggiungere WINET nella mia istanza Home Assistant
Anche se con un po' di fatica (prima di tutto, ho capito dopo che serve verificare che tutte le dipendenze siano configurate, se necessario, e poi, dopo avere copiato tutti i file, non avevo notato che dovevo copiare solo quelli senza "x3" o "blower"), sono riuscito a mettere in servizio il tuo package.
Tuttavia non riesco a configurare la parte relativa a "Crono termostato".
Dice che "non ci sono oggetti da visualizzare", ma cliccando "aggiungi", nella finestra "Nuovo orario" non posso fare nulla, mostra che non ci sono ne gruppi, ne entità, ne tanto meno azioni.
Devo fare qualcos'altro?

Grazie!

**Comment by morenonew2** [comment]
Ciao
Grazie per il feedback. Domanda di rito. Se hai installato tutto il mio
package dovresti avere una entità climate.generic_stove da usare in
cronotermostato

Il dom 27 ott 2024, 16:08 Paco1960 ***@***.***> ha scritto:

**Comment by Paco1960** [comment]
Grazie per la risposta!

Confermo che ce l'ho [https://imgur.com/Uy4KspR](url) e [https://imgur.com/UIL6pcx](url).

Però questo è cosa appare nella pagina [https://imgur.com/M8OggMy](url) e se seleziono "Aggiungi" [https://imgur.com/A4v6otH](url)

e non si riesce a fare nulla.

Qualche idea?

Grazie

**Comment by morenonew2** [comment]
Ciao
Non riesco ad aprire le immagini

Il dom 27 ott 2024, 21:32 Paco1960 ***@***.***> ha scritto:

**Comment by morenonew2** [comment]
Ciao. Sinceramente non so dirti . Io l'ho installato seguendo le info sul sito del componente. E mi ha subito visto il climate come ti dicevo. Prova magari a reinstallarlo

**Comment by Paco1960** [comment]
Grazie.
Però, quale componente devo rimuovere e reinstallare?

**Comment by morenonew2** [comment]
Scheduler

Il lun 28 ott 2024, 08:51 Paco1960 ***@***.***> ha scritto:

**Comment by morenonew2** [comment]
Ciao
Nella card prova ad andare con editor di testo e non visivo e aggiungi
sotto la card scheduler il seguente testo

include:
        - climate.generic_stove

Il lun 28 ott 2024, 10:11 Moreno ***@***.***> ha scritto:

**Comment by morenonew2** [comment]
Ho corretto i pkg c'era un bug
Stove_generic invece di generic_stove.

Grazie a te per averlo evidenziato

Il lun 28 ott 2024, 14:25 Moreno ***@***.***> ha scritto:

**Comment by Paco1960** [comment]
Scaricata la nuova versione e sostituiti tutti i file.
Perfetto!
Ora funziona!

Grazie!

**Comment by morenonew2** [comment]
Risolto
